services:
  - type: web
    name: auth-service
    env: node
    rootDir: auth-service
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5001
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: web
    name: listing-service
    env: node
    rootDir: listing-service
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5002
      - key: MONGO_URI
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  - type: web
    name: booking-service
    env: node
    rootDir: booking-service
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5003
      - key: MONGO_URI
        sync: false

  - type: web
    name: payment-service
    env: node
    rootDir: payment-service
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5005
      - key: MONGO_URI
        sync: false

  - type: web
    name: notification-service
    env: node
    rootDir: notification-service
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5004
      - key: MONGO_URI
        sync: false
